name: Build and Deploy App 

on: [push] 
jobs: 
  ci:
    environment: 
      name: Testing

    env: 
      DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}} 
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}} 
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}} 

    services: 
      postgres: 
        image: postgres

        env: 
          POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          POSTGRES_DB: ${{secrets.DATABASE_NAME}}_test 

        ports: 
          - 5432:5432

        options: >- 
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest  
    steps: 
      - name: pull git repo
        uses: actions/checkout@v2
      
      - name: setup python 
        uses: actions/setup-python@v2 
        with: 
          python-version: "3.13" 

      - name: upgrade pip 
        run: python -m pip install --upgrade pip 

      - name: install dependencies
        run: pip install -r requirements.txt 

      - name: run tests 
        run: pytest -v